import { FETCH_CATEGORIES, FETCH_SINGLE_CATEGORY } from './categories'
import { FETCH_ALL_PRODUCTS, GET_ONE_PRODUCT } from './products'
import { FETCH_ALL_TYPES, GET_ONE_TYPE } from './types'

export {
  FETCH_CATEGORIES,
  FETCH_SINGLE_CATEGORY,
  FETCH_ALL_PRODUCTS,
  GET_ONE_PRODUCT,
  FETCH_ALL_TYPES,
  GET_ONE_TYPE
}
